version: '3.7'

services:

  student_db:
    image: postgres:latest
    container_name: student_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - student_db_data:/var/lib/postgresql/data/


volumes:
  student_db_data: